### ISSUE TITLE
Expose information related to tree.

### ISSUE THREAD

**Issue by surfertas** [mrhooray/kdtree-rs#16]
Is it possible to expose information related to the tree during construction? (e.g number of leafs generated thus far.)

**Comment by mrhooray** [comment]
believe this can be done through keeping records of things or traversals

@etrombly mentioned current fields are private during #17 
what if we make them public and so that nodes can be traversed in non performance sensitive cases?
any downsides/concerns of making tree node fields public?

**Comment by mrhooray** [comment]
closing as stale. reopen if needed.
