### ISSUE TITLE
What is a computational complexity of queuing nearest point?

### ISSUE THREAD

**Issue by ababo** [mrhooray/kdtree-rs#38]
For unknown reason the `kdtree-rs` library takes about 1000x more time than Python's `sklearn.neighbors.KDTree` for very large datasets (like several millions of points). Can you confirm we have O(log(n)) for the nearest point query?

**Comment by alvarozamora** [comment]
kiddo does a comparison between kd-tree's implementation and their own. they have plots of the results which you can inspect

**Comment by ababo** [comment]
I did use it wrong, closing the issue.
