### ISSUE TITLE
Do you have a plan to upgrade the version of crate ?

### ISSUE THREAD

**Issue by cdragon-choi** [mrhooray/kdtree-rs#41]
Hello ,  
First of all, thank you for your work.
I'm planning to use your kdtree crate in rust.
In my checking, the latest crate version is 0.6.0 , which is almost 3 years ago.
But it seems that git hub has more commits after it.
Do you have a plan to upgrade the version of crate ?

**Comment by mrhooray** [comment]
published new version with recent changes
https://crates.io/crates/kdtree
