### ISSUE TITLE
Release a new Version

### ISSUE THREAD

**Issue by CryZe** [mrhooray/kdtree-rs#6]
It seems like a lot has changed since the last release (the documentation doesn't even match anymore). So it would be cool if you could release a new version. I'll have to use the git version directly till then I guess.

**Comment by Eh2406** [comment]
Yes a new version would be nice. I think all the changes are backwards compatible, just some new features.

**Comment by mrhooray** [comment]
@CryZe @Eh2406 just released 0.3.0 to cargo
